Repository lyonjs/shortvid.io, pull requests merged in 2023-05, with the labels that each got.

#291 feat(tracking): track usage of local generation
  src/app/Code.tsx
Labels: Size/XS

#273 feat(templates): create branded talk template
  package.json
  pnpm-lock.yaml
  remotion/compositions/templates/talk/Talks.composition.tsx
  remotion/compositions/templates/talk/branded/BrandedDetails.tsx
  remotion/compositions/templates/talk/branded/BrandedLocation.tsx
  remotion/compositions/templates/talk/branded/BrandedLogo.tsx
  remotion/compositions/templates/talk/branded/BrandedSpeaker.tsx
  remotion/compositions/templates/talk/branded/BrandedSpeakerInfos.tsx
  remotion/compositions/templates/talk/branded/BrandedTitle.tsx
  remotion/compositions/templates/talk/branded/TalkBranded.tsx
Labels: 📚 Ready for review, Size/L

#292 feat(font): create font-picker
  app/templates/event/page.tsx
  remotion/compositions/templates/event/Event.tsx
  remotion/compositions/templates/event/EventTitle.tsx
  src/app/forms/FontPicker.tsx
  src/app/hooks/onInputChange.ts
  src/data/fonts.js
Labels: 📚 Ready for review, Size/L

#300 feat(fonts): create font context and apply it
  app/templates/event/page.tsx
  remotion/Video.tsx
  remotion/compositions/templates/event/Event.tsx
  remotion/compositions/templates/event/EventTitle.tsx
  remotion/compositions/templates/event/Events.composition.tsx
  remotion/compositions/templates/sponsor/Sponsor.tsx
  remotion/design/atoms/Text.tsx
  src/app/RootLayout.tsx
  src/app/forms/FontPicker.tsx
  src/app/hooks/useSelectedFont.ts
  src/app/utils/loadFont.ts
  src/context/FontContext.tsx
Labels: 📚 Ready for review, Size/M

#308 feat(template): create template for camping des speakers
  public/images/conferences/campingDesSpeakers/backTrees.svg
  public/images/conferences/campingDesSpeakers/grass.svg
  public/images/conferences/campingDesSpeakers/groundDetails.svg
  public/images/conferences/campingDesSpeakers/logo.png
  public/images/conferences/campingDesSpeakers/logo_text.png
  public/images/conferences/campingDesSpeakers/tent.webm
  public/images/conferences/campingDesSpeakers/tentBackground.svg
  public/sounds/birds.mp3
  remotion/compositions/showcases/Showcases.composition.tsx
  remotion/compositions/showcases/camping-des-speakers/CampingDesSpeakers.composition.tsx
  remotion/compositions/showcases/camping-des-speakers/CampingDesSpeakers.tsx
  remotion/compositions/showcases/camping-des-speakers/Introduction.tsx
  remotion/compositions/showcases/camping-des-speakers/Talk.tsx
  remotion/compositions/showcases/camping-des-speakers/components/BackTrees.tsx
  remotion/compositions/showcases/camping-des-speakers/components/Details.tsx
  remotion/compositions/showcases/camping-des-speakers/components/FireCamp.tsx
  remotion/compositions/showcases/camping-des-speakers/components/FrontTrees.tsx
  remotion/compositions/showcases/camping-des-speakers/components/Grass.tsx
  remotion/compositions/showcases/camping-des-speakers/components/Ground.tsx
  remotion/compositions/showcases/camping-des-speakers/components/IntroBackground.tsx
  remotion/compositions/showcases/camping-des-speakers/components/Speakers.tsx
  remotion/compositions/showcases/camping-des-speakers/components/TalkBackground.tsx
  remotion/compositions/showcases/camping-des-speakers/components/TalkTitle.tsx
  remotion/compositions/showcases/camping-des-speakers/components/Tent.tsx
  remotion/compositions/showcases/camping-des-speakers/talks.json
  remotion/design/molecules/IconWithCaption.tsx
  remotion/design/molecules/TalkDetails.tsx
Labels: 📚 Ready for review, 🎬 Template, Size/XL

#309 feat(app): add showcase camping des speakers
  app/showcases/conferences/[conferenceName]/page.tsx
  package.json
  pnpm-lock.yaml
  src/app/NavBar.tsx
Labels: Size/XS

#313 fix(deps): update next + fix config
  next.config.js
  package.json
  pnpm-lock.yaml
Labels: 📚 Ready for review, Size/XS

#310 feat(showcase): create code in the dark video
  public/font/PressStart2P.ttf
  public/images/event/CITD-Background.png
  public/images/event/CITD-Logo.png
  public/sounds/keyboard.mp3
  remotion/compositions/showcases/Showcases.composition.tsx
  remotion/compositions/showcases/codeInTheDark/AnimatedCounter.tsx
  remotion/compositions/showcases/codeInTheDark/Background.tsx
  remotion/compositions/showcases/codeInTheDark/CodeInTheDark.composition.tsx
  remotion/compositions/showcases/codeInTheDark/CodeInTheDark.tsx
  remotion/compositions/showcases/codeInTheDark/Combo.tsx
  remotion/compositions/showcases/codeInTheDark/Details.tsx
  remotion/compositions/showcases/codeInTheDark/Organisateurs.tsx
  remotion/compositions/showcases/codeInTheDark/Spotlight.tsx
  remotion/compositions/showcases/codeInTheDark/Words.tsx
  src/app/utils/loadFont.ts
Labels: Size/M

#314 chore(setup): add postcss-nested
  package.json
  pnpm-lock.yaml
  postcss.config.js
Labels: Size/XS

#317 style(setup): adding purple variants in globals.css
  styles/globals.css
Labels: 📚 Ready for review, Size/XS

#323 fix(webapp): copy url with date not working
  app/templates/brandedTalk/page.tsx
  src/app/hooks/onInputChange.ts
Labels: Size/XS

#324 feat(refacto): use input date change
  app/templates/brandedTalk/page.tsx
  app/templates/event/page.tsx
  app/templates/layers/page.tsx
  app/templates/meetup/page.tsx
  app/templates/silhouette/page.tsx
  app/templates/sponsor/page.tsx
  app/templates/talk/page.tsx
  src/app/hooks/onInputChange.ts
  src/app/hooks/useInputChange.ts
  src/app/hooks/useInputDateChange.ts
Labels: Size/M

#333 chore(webapp): remove lyonjs assets
  app/layout.tsx
  app/page.tsx
  app/showcases/conferences/[conferenceName]/page.tsx
  app/templates/layers/page.tsx
  public/monogram-black.svg
  public/monogram-color.svg
  public/monogram-white.svg
  src/app/ActiveLink.tsx
  src/app/CopyUrlButton.tsx
  src/app/Header.tsx
  src/app/NavBar.tsx
  src/app/RootLayout.tsx
  styles/globals.css
  tailwind.config.js
Labels: Size/M

#325 chore(eslint): add no unused var rule + fix related lint errors
  .eslintrc
  app/showcases/conferences/[conferenceName]/page.tsx
  app/templates/talk/page.tsx
  package.json
  pnpm-lock.yaml
  remotion/compositions/showcases/alpescraft/Details.tsx
  remotion/compositions/showcases/camping-des-speakers/components/TalkBackground.tsx
  remotion/compositions/showcases/devoxx2023/Details.tsx
  remotion/compositions/showcases/lyonJS/Details.tsx
  remotion/compositions/showcases/lyonJS/TalkTitle.tsx
  remotion/compositions/showcases/snowcamp/Speakers.tsx
  remotion/compositions/showcases/touraineTech2023/Speakers.tsx
  remotion/compositions/templates/silhouette/Silhouette.tsx
  remotion/compositions/templates/talk/branded/BrandedLocation.tsx
  src/app/hooks/useSelectedFont.ts
  src/app/utils/formatUrlWithQuery.ts
  src/app/utils/loadFont.ts
Labels: Size/M

#341 fix(color): update code copy popup color
  src/app/Code.tsx
Labels: Size/XS
