Repository lyonjs/shortvid.io, pull requests merged in 2023-04, with the labels that each got.

#232 chore(molecule): uses avatar with caption molecule instead of talk speaker picture component
  remotion/compositions/showcases/alpescraft/Speakers.tsx
  remotion/compositions/showcases/alpescraft/SpeakersName.tsx
  remotion/compositions/showcases/devoxx2023/SpeakerName.tsx
  remotion/compositions/showcases/devoxx2023/Speakers.tsx
  remotion/compositions/showcases/lyonJS/BigSpeakers.tsx
  remotion/compositions/showcases/mixit2023/Speakers.tsx
  remotion/compositions/showcases/snowcamp/Speakers.tsx
  remotion/compositions/showcases/touraineTech2023/BigSpeakers.tsx
  remotion/compositions/showcases/touraineTech2023/Speakers.tsx
  remotion/compositions/showcases/very-tech-trip/Speakers.tsx
  remotion/compositions/templates/talk/Talk.tsx
  remotion/compositions/templates/talk/TalkSpeakerPicture.tsx
  remotion/design/molecules/AvatarWithCaption.tsx
Labels: Size/L

#242 fix(showcases): fix tourainetech video
  remotion/compositions/showcases/touraineTech2023/BigSpeakers.tsx
  remotion/compositions/showcases/touraineTech2023/Replay.tsx
  remotion/compositions/showcases/touraineTech2023/Speakers.tsx
  remotion/compositions/showcases/touraineTech2023/SponsorTouraineTech2023.tsx
  remotion/compositions/showcases/touraineTech2023/TalkTitle.tsx
  remotion/compositions/showcases/touraineTech2023/TouraineTech2023.tsx
Labels: Size/M

#243 fix(showcases): fix mixit video
  remotion/compositions/showcases/mixit2023/Mixit2023.tsx
  remotion/compositions/showcases/mixit2023/Speakers.tsx
  remotion/compositions/showcases/mixit2023/TalkTitle.tsx
Labels: Size/S

#246 fix(showcases): fix verytechtrip video
  remotion/compositions/showcases/very-tech-trip/Speakers.tsx
  remotion/compositions/showcases/very-tech-trip/TalkTitle.tsx
  remotion/compositions/showcases/very-tech-trip/VeryTechTrip.tsx
Labels: Size/S

#247 fix(showcases): fix devoxx video
  remotion/compositions/showcases/devoxx2023/Devoxx2023.tsx
  remotion/compositions/showcases/devoxx2023/SpeakerName.tsx
  remotion/compositions/showcases/devoxx2023/Speakers.tsx
  remotion/compositions/showcases/devoxx2023/TalkTitle.tsx
  remotion/compositions/showcases/devoxx2023/Title.tsx
Labels: Size/M

#241 fix(showcases): fix lyonjs video and layers
  remotion/compositions/showcases/lyonJS/BigSpeakers.tsx
  remotion/compositions/showcases/lyonJS/LayerOneSpeaker.tsx
  remotion/compositions/showcases/lyonJS/LayerTitle.tsx
  remotion/compositions/showcases/lyonJS/LayerTwoSpeaker.tsx
  remotion/compositions/showcases/lyonJS/Replay.tsx
  remotion/compositions/showcases/lyonJS/TalkTitle.tsx
Labels: Size/S

#244 fix(showcases): fix snowcamp video
  remotion/compositions/showcases/snowcamp/Snowcamp.tsx
  remotion/compositions/showcases/snowcamp/Speakers.tsx
  remotion/compositions/showcases/snowcamp/TalkTitle.tsx
Labels: Size/XS

#248 fix(showcases): fix templates videos
  remotion/compositions/templates/meetup/MeetupTitle.tsx
  remotion/compositions/templates/sponsor/SponsorMap.tsx
  remotion/compositions/templates/sponsor/SponsorName.tsx
Labels: Size/XS

#253 fix(app): update generated link with new app structures
  src/app/Code.tsx
Labels: Size/XS

#254 chore(app): update all the project with shortvid.io
  README.md
  app/layout.tsx
  app/page.tsx
  package.json
  src/app/Code.tsx
  src/app/Header.tsx
  src/app/RootLayout.tsx
Labels: 📚 Ready for review, Size/S

#250 feat(templates): add a new generic template
  app/templates/silhouette/page.tsx
  remotion/compositions/templates/Templates.composition.tsx
  remotion/compositions/templates/silhouette/Silhouette.composition.tsx
  remotion/compositions/templates/silhouette/Silhouette.tsx
  remotion/compositions/templates/silhouette/Silhouette.type.ts
  remotion/compositions/templates/silhouette/SilhouetteLogo.tsx
  remotion/compositions/templates/silhouette/SilhouettePicture.tsx
  remotion/compositions/templates/silhouette/SilhouetteTitle.tsx
Labels: 📚 Ready for review, Size/M

#237 feat(atoms): create icon with caption
  remotion/design/atoms/Atoms.composition.tsx
  remotion/design/molecules/IconWithCaption.tsx
  remotion/design/molecules/Molecules.composition.tsx
Labels: Size/S

#261 fix(atom): correct backgroundfiller default props
  remotion/design/atoms/Atoms.composition.tsx
Labels: Size/XS

#262 feat(atom): adding atoms for triangles
  remotion/compositions/showcases/lyonJS/LayerFullScreen.tsx
  remotion/compositions/showcases/lyonJS/LayerOneSpeaker.tsx
  remotion/compositions/showcases/lyonJS/LayerTwoSpeaker.tsx
  remotion/compositions/showcases/lyonJS/Replay.tsx
  remotion/compositions/showcases/touraineTech2023/LeftTriangle.tsx
  remotion/compositions/showcases/touraineTech2023/Replay.tsx
  remotion/compositions/showcases/touraineTech2023/RightTriangle.tsx
  remotion/compositions/showcases/touraineTech2023/SponsorTouraineTech2023.tsx
  remotion/compositions/showcases/touraineTech2023/TouraineTech2023.tsx
  remotion/design/atoms/Atoms.composition.tsx
  remotion/design/atoms/BackgroundTriangle.tsx
  remotion/design/components/LeftTriangle.tsx
  remotion/design/components/RightTriangle.tsx
Labels: 📚 Ready for review, Size/M

#265 feat(template): update layer template to generic
  app/screens/layers/[mode]/page.tsx
  app/showcases/conferences/[conferenceName]/page.tsx
  app/templates/layers/page.tsx
  public/lion-model.webp
  remotion/compositions/showcases/lyonJS/LayerFullScreen.tsx
  remotion/compositions/showcases/lyonJS/LayerOneSpeaker.tsx
  remotion/compositions/showcases/lyonJS/LayerTwoSpeaker.tsx
  remotion/compositions/showcases/lyonJS/LyonJS.composition.tsx
  remotion/compositions/templates/Templates.composition.tsx
  remotion/compositions/templates/layers/LayerFullScreen.tsx
  remotion/compositions/templates/layers/LayerOneSpeaker.tsx
  remotion/compositions/templates/layers/LayerTitle.tsx
  remotion/compositions/templates/layers/LayerTwoSpeaker.tsx
  remotion/compositions/templates/layers/Layers.composition.tsx
  remotion/compositions/templates/layers/layers.types.ts
  src/app/LayerByMode.tsx
  src/app/forms/colorInput.tsx
Labels: 📚 Ready for review, 🎬 Template, Size/L

#266 feat(atoms): create atom background circle noise
  package.json
  pnpm-lock.yaml
  remotion/design/atoms/Atoms.composition.tsx
  remotion/design/atoms/BackgroundCircleNoise.tsx
Labels: 📚 Ready for review, Size/S

#238 feat(molecules): create details molecule
  remotion/design/molecules/IconWithCaption.tsx
  remotion/design/molecules/Molecules.composition.tsx
  remotion/design/molecules/TalkDetails.tsx
Labels: 📚 Ready for review, Size/M

#256 feat(showcases): use details and icon with caption molecules
  remotion/compositions/showcases/alpescraft/Details.tsx
  remotion/compositions/showcases/devoxx2023/Details.tsx
  remotion/compositions/showcases/lyonJS/Details.tsx
  remotion/compositions/showcases/mixit2023/Details.tsx
  remotion/compositions/showcases/snowcamp/Details.tsx
  remotion/compositions/showcases/touraineTech2023/Details.tsx
  remotion/compositions/showcases/touraineTech2023/Type.tsx
  remotion/compositions/showcases/very-tech-trip/Details.tsx
Labels: 📚 Ready for review, Size/L

#280 feat(webapp): pre-fill inputs with query params
  app/templates/talk/page.tsx
  src/app/CopyUrlButton.tsx
  src/app/hooks/onInputChange.ts
  src/app/utils/encodeObjectValues.ts
  src/app/utils/formatUrlWithQuery.ts
Labels: 📚 Ready for review, Size/M

#282 feat(webapp): updated sponsor page with copy url button #281
  app/templates/sponsor/page.tsx
Labels: 📚 Ready for review, Size/XS

#284 feat(webapp): updated meetup page with copy url button #281
  app/templates/meetup/page.tsx
Labels: 📚 Ready for review, Size/XS
