Repository lyonjs/shortvid.io, pull requests merged in 2023-08, with the labels that each got.

#477 fix(app): fold min width applied in both sidebar
  src/app/components/sidebar/ResizeWrapper.tsx
  styles/app/components/sidebar/resizeWrapper.module.css
  styles/app/layout/main.module.css
Labels: Size/XS

#476 feat(serve): add preview regex for cors
  server.mjs
Labels: Size/XS

#488 fix(app): remove font picker
  app/templates/events/event/page.tsx
Labels: Size/XS

#468 feat(app): generate button
  __test__/app/Form.test.tsx
  __test__/app/RenderButton.test.tsx
  __test__/app/hooks/useGenerateVideo.test.ts
  __test__/app/sidebarNav.test.tsx
  __test__/app/sidebarNavMobile.test.tsx
  __test__/mocks/formConfig.mock.ts
  __test__/mocks/sideBarCompositionThumbnail.mock.tsx
  app/templates/events/event/page.tsx
  app/templates/layers/layers/page.tsx
  app/templates/meetups/meetup/page.tsx
  app/templates/sponsors/sponsor/page.tsx
  app/templates/sponsors/spotlightNewSponsor/page.tsx
  app/templates/talks/silhouette/page.tsx
  app/templates/talks/talk/page.tsx
  app/templates/talks/talkBranded/page.tsx
  package.json
  pnpm-lock.yaml
  remotion/compositions/templates/event/Event.tsx
  remotion/design/atoms/Text.tsx
  setup-jest.js
  src/app/CopyUrlButton.tsx
  src/app/forms/FontPicker.tsx
  src/app/forms/Form.tsx
  src/app/forms/FullScreenButtons.tsx
  src/app/forms/InfoCard.tsx
  src/app/forms/RenderButton.tsx
  src/app/forms/input.tsx
  src/app/forms/inputDate.tsx
  src/app/forms/selectInput.tsx
  src/app/hooks/useGenerateVideo.ts
  styles/app/common/buttons.module.css
  styles/app/common/form.module.css
  styles/app/common/infoCard.module.css
  styles/app/components/form/form.module.css
  styles/app/components/form/inputs.module.css
  styles/app/components/sidebar/sidebar.module.css
  styles/app/layout/main.module.css
  styles/globals.css
Labels: Size/L

#493 fix(app): default font not rendered
  remotion/design/atoms/Text.tsx
Labels: Size/XS

#499 chore(app): enable renovate auto merge
  renovate.json
Labels: Size/XS

#511 feat(app): update styles for buttons
  styles/app/common/buttons.module.css
  styles/globals.css
Labels: Size/XS

#510 feat(test): refacto layout - add tests
  __test__/app/landing/contact.test.tsx
  __test__/app/landing/footer.test.tsx
  __test__/app/landing/github.test.tsx
  __test__/app/landing/hero.test.tsx
  __test__/app/landing/partners.test.tsx
  __test__/app/landing/sponsors.test.tsx
  styles/app/common/buttons.module.css
  styles/globals.css
Labels: Size/M

#501 feat(app): refacto landing - add sponsors
  __test__/app/landing/contact.test.tsx
  __test__/app/landing/footer.test.tsx
  __test__/app/landing/github.test.tsx
  __test__/app/landing/hero.test.tsx
  __test__/app/landing/partners.test.tsx
  __test__/app/landing/sponsors.test.tsx
  app/page.tsx
  public/images/app/partners/dark/mixitLogo.svg
  public/images/app/partners/dark/touraineTechLogo.svg
  public/images/app/partners/light/mixitLogo.svg
  public/images/app/partners/light/touraineTechLogo.svg
  public/images/app/sponsors/dark/cleverCloudLogo.svg
  public/images/app/sponsors/dark/vercelLogo.svg
  public/images/app/sponsors/light/cleverCloudLogo.svg
  public/images/app/sponsors/light/vercelLogo.svg
  src/app/components/landingPage/Contact.tsx
  src/app/components/landingPage/Footer.tsx
  src/app/components/landingPage/Github.tsx
  src/app/components/landingPage/ListBloc.tsx
  src/app/components/landingPage/Partners.tsx
  src/app/components/landingPage/Sponsors.tsx
  src/data/config/landingPageConfig.js
  styles/app/common/buttons.module.css
  styles/app/common/card.module.css
  styles/app/layout/footer.module.css
  styles/app/layout/landing/contact.module.css
  styles/app/layout/landing/landing.module.css
  styles/app/layout/landing/listBloc.module.css
  styles/app/layout/landing/parterAndSponsors.module.css
  styles/globals.css
Labels: Size/M

#478 feat(app): refacto landing - header and hero
  __test__/app/landing/contact.test.tsx
  __test__/app/landing/footer.test.tsx
  __test__/app/landing/github.test.tsx
  __test__/app/landing/hero.test.tsx
  __test__/app/landing/partners.test.tsx
  __test__/app/landing/sponsors.test.tsx
  __test__/app/sidebarNav.test.tsx
  app/page.tsx
  next.config.js
  public/images/app/contact/antoine-carron.jpeg
  public/images/app/contact/mickael-alves.jpeg
  public/images/app/partners/dark/mixitLogo.svg
  public/images/app/partners/dark/touraineTechLogo.svg
  public/images/app/partners/light/mixitLogo.svg
  public/images/app/partners/light/touraineTechLogo.svg
  public/images/app/sponsors/dark/cleverCloudLogo.svg
  public/images/app/sponsors/dark/vercelLogo.svg
  public/images/app/sponsors/light/cleverCloudLogo.svg
  public/images/app/sponsors/light/vercelLogo.svg
  src/app/RootLayout.tsx
  src/app/components/landingPage/Card.tsx
  src/app/components/landingPage/Contact.tsx
  src/app/components/landingPage/Footer.tsx
  src/app/components/landingPage/Github.tsx
  src/app/components/landingPage/Hero.tsx
  src/app/components/landingPage/ListBloc.tsx
  src/app/components/landingPage/Partners.tsx
  src/app/components/landingPage/Sponsors.tsx
  src/app/components/sidebar/navigation/Header.tsx
  src/data/config/landingPageConfig.js
  styles/app/common/buttons.module.css
  styles/app/common/card.module.css
  styles/app/components/sidebar/sidebar.module.css
  styles/app/layout/footer.module.css
  styles/app/layout/landing/contact.module.css
  styles/app/layout/landing/hero.module.css
  styles/app/layout/landing/landing.module.css
  styles/app/layout/landing/listBloc.module.css
  styles/app/layout/landing/parterAndSponsors.module.css
  styles/app/layout/main.module.css
  styles/globals.css
Labels: Size/L
