Repository lyonjs/shortvid.io, pull requests merged in 2023-06, with the labels that each got.

#336 feat(footer): rebrand footer
  public/branding/powered-by-vercel-white.svg
  src/app/Footer.tsx
  src/app/RootLayout.tsx
  styles/app/layout/footer.module.css
Labels: Size/S

#365 feat(test): add test on footer component
  __test__/app/footer.test.tsx
  jest.config.js
  package.json
  pnpm-lock.yaml
Labels: Size/XS

#370 fix(test): remove useless title test
  __test__/atoms/title.test.tsx
Labels: Size/XS

#379 Revert "chore(deps): update dependency postcss to v8.4.24"
  package.json
  pnpm-lock.yaml
Labels: Size/XS

#377 style(home): fix video demo size & remove controls
  app/page.tsx
Labels: 📚 Ready for review, Size/XS, 👨🏼‍💻 Application

#375 feat(theme): create theming for the app
  __test__/app/footer.test.tsx
  package.json
  pnpm-lock.yaml
  public/branding/monogram-black.svg
  public/branding/monogram-color.svg
  public/branding/monogram-white.svg
  public/images/app/.gitkeep
  public/images/app/powered-by-vercel-dark.svg
  public/images/app/powered-by-vercel-light.svg
  src/app/ActiveLink.tsx
  src/app/Code.tsx
  src/app/CopyUrlButton.tsx
  src/app/Footer.tsx
  src/app/Header.tsx
  src/app/Logo.tsx
  src/app/NavBar.tsx
  src/app/RootLayout.tsx
  src/app/SwitchThemeButton.tsx
  src/app/forms/FontPicker.tsx
  src/app/forms/colorInput.tsx
  src/app/forms/input.tsx
  src/app/forms/inputDate.tsx
  src/app/forms/selectInput.tsx
  src/app/hooks/useThemeName.ts
  src/context/CustomThemeProvider.tsx
  styles/app/common/button.module.css
  styles/app/common/inputs.module.css
  styles/app/layout/footer.module.css
  styles/app/layout/logo.module.css
  styles/globals.css
  tailwind.config.js
Labels: Size/L

#382 feat(theme): updated theme button switch
  __test__/app/footer.test.tsx
  __test__/app/hooks/useSelectedTheme.test.tsx
  __test__/app/inputs/SwitchThemeButton.test.tsx
  jest.config.js
  package.json
  pnpm-lock.yaml
  public/branding/monogram-white.svg
  setup-jest.js
  src/app/Footer.tsx
  src/app/Header.tsx
  src/app/PoweredByVercel.tsx
  src/app/SwitchThemeButton.tsx
  src/app/SwitchThemeButtons.tsx
  src/app/ThemeRadioButton.tsx
  src/app/hooks/useSelectedTheme.ts
  src/app/hooks/useThemeName.ts
  styles/app/common/button.module.css
  styles/app/common/themeRadioGroup.module.css
  styles/app/layout/footer.module.css
  styles/globals.css
Labels: Size/M

#385 feat(showcase): create volcamp video
  public/images/showcases/volcamp/mountains.svg
  public/images/showcases/volcamp/volcampLogo.svg
  public/images/showcases/volcamp/volcampText.svg
  remotion/compositions/showcases/Showcases.composition.tsx
  remotion/compositions/showcases/volcamp/Volcamp.composition.tsx
  remotion/compositions/showcases/volcamp/Volcamp.tsx
  remotion/compositions/showcases/volcamp/components/Details.tsx
  remotion/compositions/showcases/volcamp/components/Eruption.tsx
  remotion/compositions/showcases/volcamp/components/Logo.tsx
  remotion/compositions/showcases/volcamp/components/Speakers.tsx
  remotion/compositions/showcases/volcamp/components/Talk.tsx
  remotion/compositions/showcases/volcamp/components/TalkTitle.tsx
  remotion/compositions/showcases/volcamp/components/Theme.tsx
  remotion/compositions/showcases/volcamp/components/Transition.tsx
  remotion/compositions/showcases/volcamp/components/Volcano.tsx
  remotion/design/molecules/IconWithCaption.tsx
  remotion/design/molecules/TalkDetails.tsx
Labels: Size/XL

#386 feat(app): add volcamp video to showcases
  app/showcases/conferences/[conferenceName]/page.tsx
  src/app/NavBar.tsx
Labels: Size/XS

#387 feat(app): create sidebar routing config
  src/data/sideBarConfig.ts
Labels: Size/M
