Repository lyonjs/shortvid.io, pull requests merged in 2023-10, with the labels that each got.

#594 feat(template): adding details component in default composition
  remotion/compositions/showcases/campingDesSpeakers/components/TalkTitle.tsx
  remotion/compositions/showcases/devfestNantes/Android.tsx
  remotion/compositions/showcases/devfestNantes/Details.tsx
  remotion/compositions/showcases/devfestNantes/DevfestNantes.composition.tsx
  remotion/compositions/showcases/devfestNantes/DevfestNantes.tsx
Labels: Size/S

#600 chore(branding): update logos on all application
  __test__/app/landing/footer.test.tsx
  __test__/app/sidebarNav.test.tsx
  __test__/app/sidebarNavMobile.test.tsx
  app/layout.tsx
  public/branding/full-logo-with-mono-vertical.svg
  public/branding/full-logo-with-mono.svg
  public/branding/full-logo.svg
  public/branding/monogram-white.svg
  public/branding/monogram.svg
  public/branding/screenshot.png
  src/app/Logo.tsx
  src/app/components/landingPage/Footer.tsx
  src/app/components/landingPage/Hero.tsx
  src/app/components/sidebar/navigation/Header.tsx
  styles/app/layout/footer.module.css
  styles/app/layout/landing/hero.module.css
  styles/app/layout/logo.module.css
Labels: Size/L

#602 chore(template): set reccuring day optionnal
  app/templates/talks/talkBranded/page.tsx
  remotion/compositions/templates/talk/branded/BrandedDetails.tsx
  remotion/compositions/templates/talk/branded/TalkBranded.tsx
  src/app/forms/Form.tsx
  src/app/forms/selectInput.tsx
Labels: Size/S

#603 chore(template): set reccuring day optionnal
  src/app/Code.tsx
  src/app/utils/encodeObjectValues.ts
Labels: Size/XS

#604 feat(template): adding loop in DevfestNantes composition
  remotion/compositions/showcases/devfestNantes/DevfestNantes.composition.tsx
  remotion/compositions/showcases/devfestNantes/DevfestNantesLoop.tsx
  remotion/compositions/showcases/devfestNantes/Dino.tsx
  remotion/compositions/showcases/devfestNantes/Logo.tsx
Labels: Size/M

#589 feat(template): add template carousel
  app/templates/carousel/carousel/page.tsx
  remotion/compositions/templates/Templates.composition.tsx
  remotion/compositions/templates/carousel/Carousel.composition.tsx
  remotion/compositions/templates/carousel/Carousel.tsx
  remotion/compositions/templates/carousel/CarouselImage.tsx
  src/app/types/template.types.ts
Labels: Size/M

#631 fix(showcase): update devfest nantes preview in app
  app/showcases/conferences/[conferenceName]/page.tsx
  src/data/config/showcases/devfestNantesConfig.ts
Labels: Size/XS
