Repository lyonjs/shortvid.io, pull requests merged in 2023-03, with the labels that each got.

#180 refactor(folders): split composition folder in separated files
  src/Video.tsx
  src/compositions/Atoms.composition.tsx
  src/compositions/Events.composition.tsx
  src/compositions/Meetup.composition.tsx
  src/compositions/Sponsors.composition.tsx
  src/compositions/Talks.composition.tsx
  src/compositions/conferences/AlpesCraft.composition.tsx
  src/compositions/conferences/Conferences.composition.tsx
  src/compositions/conferences/Devoxx.composition.tsx
  src/compositions/conferences/LyonJS.composition.tsx
  src/compositions/conferences/Mixit.composition.tsx
  src/compositions/conferences/Snowcamp.composition.tsx
  src/compositions/conferences/TouraineTech.composition.tsx
  src/compositions/conferences/VeryTechTrip.composition.tsx
Labels: 📚 Ready for review

#191 chore(ci): setup PR size labeler
  .github/workflows/pr-labeler.yml
Labels: 📚 Ready for review, Size/XS

#195 refactor(app): addings pages to app directory
  app/layout.tsx
  app/page.tsx
  app/screens/layers/[mode]/page.tsx
  app/showcases/conferences/[conferenceName]/page.tsx
  app/showcases/layout.tsx
  app/templates/event/page.tsx
  app/templates/layers/page.tsx
  app/templates/layout.tsx
  app/templates/meetup/page.tsx
  app/templates/replay/page.tsx
  app/templates/sponsor/page.tsx
  app/templates/talk/page.tsx
  next.config.js
  package.json
  pages/_app.jsx
  pages/layers/[mode].tsx
  pnpm-lock.yaml
  src/components/Code.tsx
  src/components/site/ActiveLink.tsx
  src/components/site/Header.tsx
  src/components/site/NavBar.tsx
  src/components/site/RootLayout.tsx
  tailwind.config.js
  tsconfig.json
  types/global.d.ts
Labels: 📚 Ready for review, Size/M

#227 chore(remotion): reorganise remotion preview to fit project organisation
  remotion/Video.tsx
  remotion/compositions/templates/Templates.composition.tsx
Labels: Size/XS
