Repository lyonjs/shortvid.io, pull requests merged in 2023-07, with the labels that each got.

#397 style(volcamp): fix volcamp video for prod
  app/showcases/conferences/[conferenceName]/page.tsx
  pnpm-lock.yaml
  remotion/compositions/showcases/volcamp/Volcamp.composition.tsx
  remotion/compositions/showcases/volcamp/Volcamp.tsx
  remotion/compositions/showcases/volcamp/components/Eruption.tsx
Labels: 📚 Ready for review, Size/S

#405 feat(types): refacto types
  app/showcases/conferences/[conferenceName]/page.tsx
  app/templates/replay/page.tsx
  remotion/compositions/showcases/alpescraft/AlpesCraft.tsx
  remotion/compositions/showcases/alpescraft/Speakers.tsx
  remotion/compositions/showcases/devoxx/Devoxx2023.tsx
  remotion/compositions/showcases/devoxx/Speakers.tsx
  remotion/compositions/showcases/lyonJS/BigSpeakers.tsx
  remotion/compositions/showcases/lyonJS/Replay.tsx
  remotion/compositions/showcases/mixit/Mixit2023.tsx
  remotion/compositions/showcases/mixit/MixitIntroTalk.tsx
  remotion/compositions/showcases/mixit/Speakers.tsx
  remotion/compositions/showcases/snowcamp/Snowcamp.tsx
  remotion/compositions/showcases/snowcamp/Speakers.tsx
  remotion/compositions/showcases/touraineTech/BigSpeakers.tsx
  remotion/compositions/showcases/touraineTech/Replay.tsx
  remotion/compositions/showcases/touraineTech/Speakers.tsx
  remotion/compositions/showcases/touraineTech/TouraineTech2023.tsx
  remotion/compositions/showcases/veryTechTrip/Speakers.tsx
  remotion/compositions/showcases/veryTechTrip/VeryTechTrip.tsx
  remotion/compositions/showcases/volcamp/components/Talk.tsx
  remotion/compositions/templates/layers/LayerFullScreen.tsx
  remotion/compositions/templates/layers/LayerOneSpeaker.tsx
  remotion/compositions/templates/layers/LayerTwoSpeaker.tsx
  remotion/compositions/templates/layers/layers.types.ts
  remotion/types/defaultProps.types.ts
  src/app/Code.tsx
Labels: Size/M

#404 feat(app): sidebar testing
  __test__/app/sidebar.test.tsx
  __test__/mocks/sideBarConfig.mock.ts
  src/app/components/sidebar/CompositionThumbnail.tsx
  src/app/components/sidebar/Sidebar.tsx
  src/app/components/sidebar/TopLevelContent.tsx
Labels: Size/M

#418 feat(sidebar): refacto layout
  __test__/app/footer.test.tsx
  app/templates/layers/page.tsx
  app/templates/silhouette/page.tsx
  src/app/Footer.tsx
  src/app/RootLayout.tsx
  styles/app/layout/footer.module.css
Labels: Size/S

#389 feat(app): create sidebar design
  __test__/app/footer.test.tsx
  __test__/app/sidebar.test.tsx
  __test__/mocks/sideBarConfig.mock.ts
  app/templates/layers/page.tsx
  app/templates/silhouette/page.tsx
  app/templates/talks/talk/page.tsx
  app/templates/talks/talkBranded/page.tsx
  public/images/showcases/snowcamp/snowcampLogo.png
  remotion/compositions/showcases/veryTechTrip/Logo.tsx
  src/app/ActiveLink.tsx
  src/app/Footer.tsx
  src/app/Header.tsx
  src/app/NavBar.tsx
  src/app/RootLayout.tsx
  src/app/components/sidebar/ActiveLink.tsx
  src/app/components/sidebar/CategoryLink.tsx
  src/app/components/sidebar/CompositionThumbnail.tsx
  src/app/components/sidebar/Footer.tsx
  src/app/components/sidebar/Header.tsx
  src/app/components/sidebar/Nav.tsx
  src/app/components/sidebar/NavDetails.tsx
  src/app/components/sidebar/Sidebar.tsx
  src/app/components/sidebar/TopLevelContent.tsx
  src/app/hooks/useCompositionConfig.ts
  src/data/config/compositionsConfig.ts
  src/data/config/showcases/alpesCraftConfig.ts
  src/data/config/showcases/campingDesSpeakersConfig.ts
  src/data/config/showcases/devoxxConfig.ts
  src/data/config/showcases/mixitConfig.ts
  src/data/config/showcases/snowcampConfig.ts
  src/data/config/showcases/touraineTechConfig.ts
  src/data/config/showcases/veryTechTripConfig.ts
  src/data/config/showcases/volcampConfig.ts
  src/data/config/sideBarConfig.ts
  src/data/config/templates/eventConfig.ts
  src/data/config/templates/layersConfig.ts
  src/data/config/templates/meetupConfig.ts
  src/data/config/templates/silhouetteConfig.ts
  src/data/config/templates/sponsorConfig.ts
  src/data/config/templates/talkBrandedConfig.ts
  src/data/config/templates/talkConfig.ts
  src/data/sideBarConfig.ts
  styles/app/common/themeRadioGroup.module.css
  styles/app/components/sidebar/activeLink.module.css
  styles/app/components/sidebar/nav.module.css
  styles/app/components/sidebar/sidebar.module.css
  styles/app/layout/footer.module.css
  styles/app/layout/main.module.css
  styles/globals.css
Labels: Size/XL

#428 chore(deps): update dependency next to v13.4.10
  package.json
  pnpm-lock.yaml
Labels: Size/XS

#409 feat(app): saving sidebar folded preference
  __test__/app/sidebar.test.tsx
  src/app/hooks/useSidebarPreferences.ts
  src/context/SidebarContext.tsx
Labels: 📚 Ready for review, Size/XS

#416 feat(sidebar): add responsive
  __test__/app/ResizeWrapper.test.tsx
  __test__/app/sidebar.test.tsx
  __test__/app/sidebarMobile.test.tsx
  __test__/mocks/sideBarCompositionThumbnailMock.tsx
  src/app/RootLayout.tsx
  src/app/components/sidebar/Header.tsx
  src/app/components/sidebar/ResizeWrapper.tsx
  src/app/components/sidebar/navigation/BurgerIcon.tsx
  src/app/components/sidebar/navigation/CategoryLink.tsx
  src/app/components/sidebar/navigation/CompositionThumbnail.tsx
  src/app/components/sidebar/navigation/Footer.tsx
  src/app/components/sidebar/navigation/Header.tsx
  src/app/components/sidebar/navigation/Nav.tsx
  src/app/components/sidebar/navigation/NavDetails.tsx
  src/app/components/sidebar/navigation/Sidebar.tsx
  src/app/components/sidebar/navigation/SidebarMobile.tsx
  src/app/hooks/useSidebarPreferences.ts
  src/context/SidebarContext.tsx
  styles/app/components/sidebar/activeLink.module.css
  styles/app/components/sidebar/nav.module.css
  styles/app/components/sidebar/resizeWrapper.module.css
  styles/app/components/sidebar/sidebar.module.css
  styles/app/layout/main.module.css
  styles/globals.css
Labels: 📚 Ready for review, Size/L

#439 refactor(resize): avoid useEffect dependencies change on every render
  src/app/components/sidebar/ResizeWrapper.tsx
Labels: 📚 Ready for review, 👨🏼‍💻 Application

#446 feat(app): only display footer on homepage
  app/layout.tsx
  app/page.tsx
  src/app/RootLayout.tsx
  styles/app/layout/footer.module.css
Labels: 📚 Ready for review, Size/M, 👨🏼‍💻 Application

#438 feat(server): setup express server side rendering of videos
  .clever.json
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  server.mjs
Labels: 🚀 Feature, Size/M

#452 feat(app): fixed sidebar
  src/app/RootLayout.tsx
  styles/app/layout/main.module.css
Labels: Size/XS, 👨🏼‍💻 Application

#442 feat(app): layout responsive with sidebar right
  app/templates/events/event/page.tsx
  app/templates/layers/layers/page.tsx
  app/templates/layout.tsx
  app/templates/meetups/meetup/page.tsx
  app/templates/sponsors/sponsor/page.tsx
  app/templates/sponsors/spotlightNewSponsor/page.tsx
  app/templates/talks/silhouette/page.tsx
  app/templates/talks/talk/page.tsx
  app/templates/talks/talkBranded/page.tsx
  src/app/forms/Form.tsx
  src/app/forms/FullScreenButtons.tsx
  src/app/forms/inputDate.tsx
  src/app/hooks/useInputDateChange.ts
  styles/app/components/sidebar/resizeWrapper.module.css
  styles/app/components/sidebar/sidebar.module.css
  styles/app/layout/main.module.css
Labels: Size/XL

#441 feat(app): created sidebar right with form
  __test__/app/ResizeWrapper.test.tsx
  __test__/app/sidebarNav.test.tsx
  __test__/app/sidebarNavMobile.test.tsx
  app/showcases/conferences/[conferenceName]/page.tsx
  app/templates/events/event/page.tsx
  app/templates/layers/layers/page.tsx
  app/templates/layout.tsx
  app/templates/meetups/meetup/page.tsx
  app/templates/sponsors/sponsor/page.tsx
  app/templates/sponsors/spotlightNewSponsor/page.tsx
  app/templates/talks/silhouette/page.tsx
  app/templates/talks/talk/page.tsx
  app/templates/talks/talkBranded/page.tsx
  src/app/Code.tsx
  src/app/CopyUrlButton.tsx
  src/app/RootLayout.tsx
  src/app/components/sidebar/ResizeWrapper.tsx
  src/app/components/sidebar/Sidebar.tsx
  src/app/components/sidebar/navigation/SidebarNav.tsx
  src/app/components/sidebar/navigation/SidebarNavMobile.tsx
  src/app/forms/Form.tsx
  src/app/forms/FullScreenButtons.tsx
  src/app/forms/input.tsx
  src/app/forms/inputDate.tsx
  src/app/hooks/useInputDateChange.ts
  styles/app/common/buttons.module.css
  styles/app/common/form.module.css
  styles/app/components/sidebar/nav.module.css
  styles/app/components/sidebar/resizeWrapper.module.css
  styles/app/components/sidebar/sidebar.module.css
  styles/app/layout/main.module.css
  styles/globals.css
Labels: Size/XL

#466 fix(sidebar): resize an scroll overflow
  styles/app/common/form.module.css
  styles/app/components/sidebar/nav.module.css
  styles/app/components/sidebar/resizeWrapper.module.css
Labels: Size/XS
