Repository lyonjs/shortvid.io, pull requests merged in 2024-08, with the labels that each got.

#1144 feat(volcamp): adding zod schema for Volcamp showcases
  remotion/compositions/showcases/showcases.types.ts
  remotion/compositions/showcases/volcamp/Volcamp.composition.tsx
Labels: Size/XS

#1147 feat(template/Talk): adding color picker on talk template
  app/templates/talks/talk/page.tsx
  remotion/compositions/templates/talk/SpeakerAndTitle.tsx
  remotion/compositions/templates/talk/Talk.tsx
  remotion/compositions/templates/talk/Talks.composition.tsx
  remotion/compositions/templates/talk/talks.types.ts
  src/app/forms/Form.tsx
  src/app/hooks/useInputChange.ts
  src/data/config/compositionsConfig.ts
  src/data/config/templates/talkConfig.ts
Labels: Size/S

#1148 ci(editor): deploy editor workflow setup
  .github/workflows/deploy-editor.yml
  Dockerfile.editor
  package.json
  remotion/compositions/templates/event/Event.tsx
  remotion/design/atoms/Text.tsx
Labels: Size/S

#1156 ci(editor): deploy editor workflow setup
  remotion/compositions/templates/layers/LayerFullScreen.tsx
  remotion/compositions/templates/layers/LayerOneSpeaker.tsx
  remotion/compositions/templates/layers/LayerTwoSpeaker.tsx
  remotion/compositions/templates/layers/Layers.composition.tsx
  remotion/compositions/templates/layers/layers.types.ts
Labels: Size/S

#1159 feat(app): drop showcase page
  app/showcases/conferences/[conferenceName]/page.tsx
  app/showcases/layout.tsx
  src/data/config/compositionsConfig.ts
  src/data/config/showcases/alpesCraftConfig.ts
  src/data/config/showcases/campingDesSpeakersConfig.ts
  src/data/config/showcases/devfestLilleConfig.ts
  src/data/config/showcases/devfestNantesConfig.ts
  src/data/config/showcases/devoxxConfig.ts
  src/data/config/showcases/mixitConfig.ts
  src/data/config/showcases/snowcampConfig.ts
  src/data/config/showcases/touraineTechConfig.ts
  src/data/config/showcases/veryTechTripConfig.ts
  src/data/config/showcases/volcampConfig.ts
  src/data/config/sideBarConfig.ts
Labels: Size/M

#1157 feat(website): drop layer feature from website
  app/screens/layers/[mode]/page.tsx
  app/templates/layers/layers/page.tsx
  src/app/LayerByMode.tsx
  src/app/types/layerMode.types.ts
  src/app/types/template.types.ts
  src/data/config/compositionsConfig.ts
  src/data/config/sideBarConfig.ts
  src/data/config/templates/layersConfig.ts
Labels: Size/M

#1158 feat(remotion): add zod schema for sponsors
  remotion/compositions/templates/sponsors/Sponsors.composition.tsx
  remotion/compositions/templates/sponsors/sponsors.types.ts
  remotion/compositions/templates/sponsors/spotlightNewSponsor/SpotlightNewSponsor.tsx
Labels: Size/XS
